### ISSUE TITLE
Zmiana obliczeń na slave z 1 task per wywołanie kernela

### ISSUE THREAD

**Issue by MAJ0RRR** [MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap#32]
czyli w 1 tasku tworzone jest N wątków) na N tasków per wywołanie kernela gdzie N to liczba corów + przetestowanie czy takie rozwiązanie coś zmienia

#10 #30 #31

**Comment by huwzpf** [comment]
Przetestowałem różne opcje na to (https://github.com/MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap/tree/launch-multiple-tasks https://github.com/MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap/tree/launch-multiple-tasks-2) I wygląda że to jednak słaby pomysł. Zamykam issue.
