### ISSUE TITLE
Napisanie kodu ustawiania power capów przez NVML / RAPL

### ISSUE THREAD

**Issue by MAJ0RRR** [MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap#33]

**Comment by huwzpf** [comment]
Libki z których można skorzystać żeby samemu nie handlować tych plików: 
https://github.com/powercap/raplcap
I chyba (ta pierwsza jakoś używa tej ale nie wiem jaka jest różnica dokładnie między nimi) https://github.com/powercap/powercap

**Comment by huwzpf** [comment]
Zgodnie z decyzją na spotkaniu nie będziemy implementować powercapów przez NVML / RAPL
