### ISSUE TITLE
Modyfikacja kodu power cappingu tak, żeby dawał możliwość wyboru konkretnego sposobu

### ISSUE THREAD

**Issue by MAJ0RRR** [MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap#34]

**Comment by huwzpf** [comment]
Można zacząć od kodu który włącza / wyłącza power cap na podstawie opcji  podanej do libki (np `__cudampi__setPowerCappingMethod (enum PowerCappingMethod)` gdzie opcje to `OFF, GREEDY`)

**Comment by huwzpf** [comment]
Zgodnie z decyzją na spotkaniu nie będziemy implementować powercapów przez NVML / RAPL
