### ISSUE TITLE
Impelemntacja prostych algorytów rozdziału power capów 

### ISSUE THREAD

**Issue by MAJ0RRR** [MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap#35]
#34 #33

**Comment by huwzpf** [comment]
Proste algorytmy jakie ja bym widziała na start to: 
1. Zmiana greedy tak żeby przypisywał gdzieś pozostały power cap
2. Przypisujemy wszędzie minimalny power cap i pozostałą wartość obdzielamy na najbardziej efektywne urządzenia
3. Dzielimy power cap po równo na wszystkie devices (np proporcjonalnie do ich minimalnego power capa albo w ogóle po równo)

Potem można pomyśleć o jakimś iteracyjnym algorytmie który dynamicznie przypisuje te power capy

**Comment by huwzpf** [comment]
Zgodnie z decyzją na spotkaniu nie będziemy implementować powercapów przez NVML / RAPL
