### ISSUE TITLE
Implementacja logiki alokacji danych na CPU - Malloc i Free

### ISSUE THREAD

**Issue by MAJ0RRR** [MAJ0RRR/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap#7]

**Comment by GeislerAgata** [comment]
Spotkanie 04.09

dev - wersja bazowa kodu, ale nie wiadomo czy działa - trzeba dojść który branch jest aktualnie bazowy

Implementacja logiki alokacji danych na CPU - Malloc i Free
- trzeba stworzyć branch do naszego zadania - zapytać z którego branch weźmiemy korzystać, bo teraz nie wiadomo

cudamplib.c 
- cudampi_malloc - tą funkcję i free trzeba przepisać, tak, żeby korzystała nie tylko z cudy, ale też żeby korzystała z CPU
- tutaj piszemy tylko mastera

cudampislave.c
- slave'y są w cudampi_slave.c - tam je będziemy pisać
- CUDAMPIMALLOCREQ i CUDAMPIFREEREQ - slave do malloc'a - je też trzeba będzie przerobić
- ify to są slave'y dla konkretnych tagów

trzeba przenalizować ten kod - deadline piątek po pracy

**Comment by MAJ0RRR** [comment]
> Spotkanie 04.09
> 
> dev - wersja bazowa kodu, ale nie wiadomo czy działa - trzeba dojść który branch jest aktualnie bazowy
> 
> Implementacja logiki alokacji danych na CPU - Malloc i Free
> 
> * trzeba stworzyć branch do naszego zadania - zapytać z którego branch weźmiemy korzystać, bo teraz nie wiadomo
> 
> cudamplib.c
> 
> * cudampi_malloc - tą funkcję i free trzeba przepisać, tak, żeby korzystała nie tylko z cudy, ale też żeby korzystała z CPU
> * tutaj piszemy tylko mastera
> 
> cudampislave.c
> 
> * slave'y są w cudampi_slave.c - tam je będziemy pisać
> * CUDAMPIMALLOCREQ i CUDAMPIFREEREQ - slave do malloc'a - je też trzeba będzie przerobić
> * ify to są slave'y dla konkretnych tagów
> 
> trzeba przenalizować ten kod - deadline piątek po pracy

master - branch działający, z drobnymi zmianami nie psującymi
dev - branch z najnowszymi zmianami z I etapu, jest jeszcze trochę rzeczy do uzupełnienia, więc on nie działa, jak wprowadzimy już wszystkie zmiany to będziemy próbować go postawić
Wasz branch powinien być odbity od dev'a.
